spring:
  application:
    name: eureka-server
server:
  port: 7001
eureka:
  instance:
    hostname: server2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/
