server:
  port: 13000

management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  cloud:
    config:
      name: config-client
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: config-server
    bus:
      trace:
        enabled: true
      enabled: true

# 注册到eureka
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7000/eureka/